name: clean-npm-packages-prebuilds
on:
  workflow_dispatch:
jobs:
  cleanup-npm-native-dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        packages: 
          - '@hackolade/desktop-trampoline-darwin-arm64'
          - '@hackolade/desktop-trampoline-win32-x64'
          - '@hackolade/kerberos-linux-x64'
          - '@hackolade/keytar-darwin-x64'
          - '@hackolade/mongodb-client-encryption-darwin-arm64'
          - '@hackolade/mongodb-client-encryption-win32-x64'
          - '@hackolade/watcher-linux-arm64-glib'
          - '@hackolade/desktop-trampoline-darwin-x64'
          - '@hackolade/kerberos-darwin-arm64'
          - '@hackolade/kerberos-win32-x64'
          - '@hackolade/keytar-linux-x64'
          - '@hackolade/mongodb-client-encryption-darwin-x64	'
          - '@hackolade/watcher-darwin-arm64'
          - '@hackolade/watcher-linux-x64-glibc'
          - '@hackolade/desktop-trampoline-linux-x64'
          - '@hackolade/kerberos-darwin-x64'
          - '@hackolade/keytar-darwin-arm64'
          - '@hackolade/keytar-win32-x64'
          - '@hackolade/mongodb-client-encryption-linux-x64'
          - '@hackolade/watcher-darwin-x64'
          - '@hackolade/watcher-win32-x64'
    steps:
      - uses: actions/delete-package-versions@v4
        with:
          package-name: ${{ matrix.packages }}
          package-type: 'npm'
          min-versions-to-keep: 0



          