name: Prebuilds

on:
  workflow_dispatch:

jobs:
  build-for-linux:
    runs-on: ubuntu-22.04
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 18
      - name: Download list of modules to rebuild for Electron
        uses: actions/download-artifact@v3
        with:
          name: modulesToBuildForElectron
      - name: Install krb5
        run: sudo apt-get install -y libkrb5-dev

      - name: Install toolkit
        run: npm install
      - name: Build native modules on Linux x64
        run: npm run rebuild-custom-for-target
